# permissions for end users to edit postgresqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresql-editor-role
rules:
- apiGroups:
  - database.iboware.com
  resources:
  - postgresqls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.iboware.com
  resources:
  - postgresqls/status
  verbs:
  - get
