apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgresqls.postgresql.iboware.com
spec:
  group: postgresql.iboware.com
  names:
    kind: PostgreSQL
    listKind: PostgreSQLList
    plural: postgresqls
    singular: postgresql
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: PostgreSQL is the Schema for the postgresqls API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: PostgreSQLSpec defines the desired state of PostgreSQL
            properties:
              disksize:
                description: 'DiskSize is the persistent volume siz of the PostgreSQL
                  deployment. (example: 8Gi,10Gi)'
                type: string
              replicas:
                description: Replicas is the size of the PostgreSQL deployment
                format: int32
                type: integer
            required:
            - disksize
            - replicas
            type: object
          status:
            description: PostgreSQLStatus defines the observed state of PostgreSQL
            properties:
              nodes:
                description: Nodes are the names of the PostgreSQL pods
                items:
                  type: string
                type: array
            required:
            - nodes
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
